//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiViet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaiViet()
        {
            this.QlTuongTacs = new HashSet<QlTuongTac>();
        }
    
        public string MaBaiViet { get; set; }
        public string TenBaiViet { get; set; }
        public string TheLoai { get; set; }
        public string NguoiViet { get; set; }
        public Nullable<System.DateTime> NgayViet { get; set; }
        public string NoiDung { get; set; }
    
        public virtual DanhMuc DanhMuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QlTuongTac> QlTuongTacs { get; set; }
    }
}
