//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardGame
    {
        public string SeRi { get; set; }
        public string MaNap { get; set; }
        public string NPH { get; set; }
        public Nullable<double> MenhGia { get; set; }
        public Nullable<System.DateTime> HanDung { get; set; }
    }
}
