//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class QlPhanHoi
    {
        public string IDPhanHoi { get; set; }
        public string IDNguoiPH { get; set; }
        public string TenNguoiPH { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayGui { get; set; }
        public string Email { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
