//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class QlTuongTac
    {
        public System.DateTime Ngay { get; set; }
        public string IDBaiViet { get; set; }
        public Nullable<double> SoTT { get; set; }
    
        public virtual BaiViet BaiViet { get; set; }
    }
}
